language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
# don't enable gui tests yet, since they still need to be finished
#script: mvn -DguiTests test
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
