#!/bin/sh

# Initialize the $KEY_DIR directory.
# Note that this script does a
# rm -rf on $KEY_DIR so be careful!

if [ "$KEY_DIR" ]; then
	# slightly changed from original source to allow for failure when
	# ownership of key directory is not by the running (web) user
	[ ! -d "$KEY_DIR" ] && mkdir "$KEY_DIR"
    rm -rf "$KEY_DIR/*"
	chmod go-rwx "$KEY_DIR"
	touch "$KEY_DIR/index.txt"
	echo 01 >"$KEY_DIR/serial"
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
